
import { Category, WordPair, TranslationSet, Language } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'country', ar: 'دولة 🌍', en: 'Country 🌍' },
  { id: 'team', ar: 'نادي ⚽', en: 'Football Team ⚽' },
  { id: 'player', ar: 'لاعب 🏃‍♂️', en: 'Famous Player 🏃‍♂️' },
  { id: 'food', ar: 'طعام 🍔', en: 'Food 🍔' },
];

export const INITIAL_WORDS: WordPair[] = [
  { id: '1', categoryId: 'country', secret: 'السعودية' },
  { id: '2', categoryId: 'country', secret: 'مصر' },
  { id: '3', categoryId: 'team', secret: 'الهلال' },
  { id: '4', categoryId: 'team', secret: 'ريال مدريد' },
  { id: '5', categoryId: 'player', secret: 'ميسي' },
  { id: '6', categoryId: 'food', secret: 'كبسة' },
];

export const TRANSLATIONS: Record<Language, TranslationSet> = {
  ar: {
    title: 'مين امبوستر؟',
    createRoom: 'إنشاء غرفة',
    joinRoom: 'دخول غرفة',
    enterName: 'ادخل اسمك',
    roomCode: 'رمز الغرفة',
    start: 'بدء اللعبة',
    category: 'الفئة',
    imposters: 'عدد الامبوسترز',
    wordSource: 'مصدر الكلمات',
    playersCount: 'اللاعبين',
    discussion: 'وقت النقاش',
    voteNow: 'صوّت الآن',
    results: 'النتائج',
    points: 'النقاط',
    imposter: 'امبوستر',
    detective: 'مواطن',
    judge: 'حكم',
    yourWord: 'كلمتك هي:',
    system: 'النظام',
    manual: 'يدوي (حكم)',
    open: 'مفتوح',
    timed: 'موقت',
    readyToVote: 'جاهز للتصويت',
    guessWord: 'الامبوستر يحاول تخمين الكلمة...',
    winner: 'الفائز',
    backToLobby: 'العودة للوبي',
    adminDashboard: 'لوحة التحكم العامة',
    roomSettings: 'إعدادات الغرفة',
    timeLimit: 'وقت المناقشة',
    minutes: 'دقائق',
    shareWithFriends: 'شارك مع الأصدقاء',
    suggestionsBox: 'صندوق المقترحات',
    gameGuide: 'دليل اللعبة',
    howToPlay: 'كيف تلعب؟',
    rule1: 'الكل يحصل على كلمة سرية، إلا الامبوستر لا يعرف الكلمة وعليه التخفي!',
    rule2: 'المضيف يمكنه اختيار مصدر الكلمات من النظام أو تعيين "حكم" يكتب الكلمات يدوياً.',
    rule3: 'يصف كل لاعب كلمته بكلمة واحدة، والامبوستر يحاول الاندماج بذكاء دون اكتشافه.',
    close: 'إغلاق',
    imposterAlert: '⚠️ أنت الامبوستر! 🎭',
    categoryInput: 'اسم التصنيف (مثلاً: سيارات)',
  },
  en: {
    title: 'Min Imposter',
    createRoom: 'Create Room',
    joinRoom: 'Join Room',
    enterName: 'Enter Name',
    roomCode: 'Room Code',
    start: 'Start Game',
    category: 'Category',
    imposters: 'Imposters',
    wordSource: 'Word Source',
    playersCount: 'Players',
    discussion: 'Discussion Time',
    voteNow: 'Vote Now',
    results: 'Results',
    points: 'Points',
    imposter: 'Imposter',
    detective: 'Citizen',
    judge: 'Judge',
    yourWord: 'Your word is:',
    system: 'System',
    manual: 'Manual (Judge)',
    open: 'Open',
    timed: 'Timed',
    readyToVote: 'Ready to Vote',
    guessWord: 'Imposter is guessing the word...',
    winner: 'Winner',
    backToLobby: 'Back to Lobby',
    adminDashboard: 'General Admin',
    roomSettings: 'Room Settings',
    timeLimit: 'Discussion Time',
    minutes: 'Min',
    shareWithFriends: 'Share with Friends',
    suggestionsBox: 'Suggestions Box',
    gameGuide: 'Game Guide',
    howToPlay: 'How to Play?',
    rule1: 'Everyone gets a secret word, except the imposter who doesn\'t know it and must hide!',
    rule2: 'Host can use system words or assign a "Judge" to enter words manually.',
    rule3: 'Each player gives a one-word clue. The imposter must blend in without getting caught.',
    close: 'Close',
    imposterAlert: '⚠️ YOU ARE THE IMPOSTER! 🎭',
    categoryInput: 'Category Name (e.g., Cars)',
  },
};
